### ISSUE TITLE
javascript online site is down

### ISSUE THREAD

**Issue by JLuc** [viznut/IBNIZ#15]
http://ibniz.asiekierka.pl/ibniz.html site for "On-line Javascript implementation" is down.
(link found here : http://pelulamu.net/ibniz/)

**Comment by denilsonsa** [comment]
That old URL is now available at http://ibniz.breizh-entropy.org/ (and also https://github.com/asiekierka/ibnjs )

Someone else created another JavaScript implementation:

* https://github.com/flupe/jibniz
* https://flupe.github.io/jibniz/

**Comment by denilsonsa** [comment]
@viznut Can you also please update the URL in the README file and in the GitHub project description?

And if this is a completely static website, you may even consider setting it up on [GitHub Pages](https://pages.github.com/), so you won't have to worry about custom DNS nor servers.

**Comment by viznut** [comment]
Pelulamu.net is temporarily down, but I guess viznut.fi is a more proper site for this anyway.
